### ISSUE TITLE
Change Alerts to something else

### ISSUE THREAD

**Issue by podfeet** [NosillaCast/a-world-clock#16]
Idea 1: make the copy button actually copy the URL without showing it and have a toast that says "a URL has been copied for you to send to someone" or "A sendable URL has been copied to your clipboard. Paste it somewhere."

**Comment by NosillaCast** [comment]
Important because alerts can't be copied on Chrome

**Comment by podfeet** [comment]
Changed to copy button creating a text area and then copying it. Trying to get it to go away after creation but technically this issue is fixed.
